eclipse-mylyn/org.eclipse.mylyn

- org.eclipse.mylyn.releng/oomph/Mylyn.setup
fix the names by adding suffix  -parent
> fix: update Mylyn.setup to work with GitHub

- org.eclipse.mylyn.releng/oomph/MylynConfiguration.setup
For the Eclipse Installer update link we need to change the stream to main
> Change Stream to main

- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/PersonProposalProvider.java
see https://github.com/eclipse-mylyn/org.eclipse.mylyn.tasks/issues/12
> PersonProposalProvider searches change

- mylyn.releng/org.eclipse.mylyn.parent/pom.xml
> Releng: update the list of supported environments

- org.eclipse.mylyn-target/mylyn-e4.26.target
Remove circularity
Signed-off-by: Alexander Fedorov <alexander.fedorov@arsysop.ru>
> target platform strategy #22

- .github/workflows/licensecheck.yml
- mylyn.versions/org.eclipse.mylyn.versions.development-feature/feature.xml
- mylyn.versions/pom.xml
- org.eclipse.mylyn-site/category.xml
Remove org.eclipse.mylyn.subclipse-feature from site 
Remove org.eclipse.mylyn.subclipse-feature and its bundles from reactor
> Remove Subclipse integration from distribution #47

- mylyn.commons/org.eclipse.mylyn.development/Bootstrap/Mylyn-Work-Mac.launch
- mylyn.commons/org.eclipse.mylyn.development/Bootstrap/Mylyn-Work.launch
- mylyn.commons/org.eclipse.mylyn.development/Work/Mylyn-Runtime-Mac.launch
- mylyn.commons/org.eclipse.mylyn.development/Work/Mylyn-Runtime.launch
- mylyn.commons/org.eclipse.mylyn.development/Work/local-All-BugzillaTests.launch
- mylyn.commons/org.eclipse.mylyn.development/Work/local-All-TaskTests.launch
- mylyn.commons/org.eclipse.mylyn.development/Work/local-All-TracTests.launch
- mylyn.commons/org.eclipse.mylyn.development/Work/local-Default-BugzillaTests.launch
- mylyn.commons/org.eclipse.mylyn.development/Work/local-Single-BugzillaTests.launch
Short term fix until the base level has been decided on
> launch files expect JavSE-1.6 #53

- mylyn.releng/org.eclipse.mylyn.parent/pom.xml
- org.eclipse.mylyn-site/category.xml
- org.eclipse.mylyn.releng/oomph/Mylyn.setup
First part of making Trac as an installable feature (see
[Trac Connector should be a installable feature](https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/17)
> only the real changes the refactoring would be an other change

- mylyn.builds/org.eclipse.mylyn.hudson.core/META-INF/MANIFEST.MF
Sudden unresolved reference to jakarta.activation-api 1.2.2
> Unable to resolve jakarta.activation-api 1.2.2 #55

- org.eclipse.mylyn-site/category.xml
see: https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/74
> Issue #74: remove Gerrit Connector from Download Site

- mylyn.github/org.eclipse.mylyn.github.ui/src/org/eclipse/mylyn/internal/github/ui/issue/IssueTaskEditorPage.java
Don't try to use a null pointer
> Fix NPE associated with GitHub Isses when Anonymous #78

- .github/dependabot.yml
> Employ dependabot for org.eclipse.mylyn repository #88

- org.eclipse.mylyn-target/mylyn-e4.26.target
Remove unnecessary maven egit repo
> [#103] Manage External Dependencies

- org.eclipse.mylyn-target/mylyn-e4.26.target
https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/103
https://github.com/eclipse-mylyn/.github/issues/23
> Get Maven dependencies needing a generated OSGi MANIFEST.MF centrally

- mylyn.github/org.eclipse.mylyn.github-feature/feature.xml
- mylyn.reviews/org.eclipse.mylyn.gerrit.dashboard.feature/feature.xml
- mylyn.tasks/org.eclipse.mylyn.test-feature/feature.xml
https://download.eclipse.org/oomph/archive/reports-extra/mylyn/download.eclipse.org/mylyn/stage/latest/index.html
* Providers 2 (1 Not Provided by Eclipse)
* Features 40 (2 No Branding Images)
> Fix update site analyzer report

- org.eclipse.mylyn-site/category.xml
Add required bundles from TP to P2 repository
Fixes #111
> [#111] Need javax.activation and lucene.queries.intervals

- org.eclipse.mylyn-site/category.xml
See https://ci.eclipse.org/simrel/job/simrel.runaggregator.VALIDATE.gerrit/3499/console
> Add more 3rd party libs to make SimRel happy

- CODE_OF_CONDUCT.md
Requested at
https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/484
> Add CODE_OF_CONDUCT.MD

- mylyn.commons/org.eclipse.mylyn.discovery.tests/META-INF/MANIFEST.MF
- mylyn.egit/org.eclipse.egit.mylyn.ui.test/META-INF/MANIFEST.MF
- mylyn.github/org.eclipse.mylyn.github.tests/META-INF/MANIFEST.MF
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.core.tests/META-INF/MANIFEST.MF
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.core/META-INF/MANIFEST.MF
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.ui/META-INF/MANIFEST.MF
- mylyn.tasks/org.eclipse.mylyn.tasks.activity.tests/META-INF/MANIFEST.MF
- mylyn.tasks/org.eclipse.mylyn.tasks.index.tests/META-INF/MANIFEST.MF
- org.eclipse.mylyn.discovery-directory/META-INF/MANIFEST.MF
- org.eclipse.mylyn.discovery-directory/plugin.properties
https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/128
> Use consistent bundle and vendor names

- org.eclipse.mylyn.releng/oomph/Mylyn.setup
> 127 api baseline

- org.eclipse.mylyn.releng/oomph/Mylyn.setup
Also remove the old API baseline task in favor of the new targlets.based task.
> Improve Mylyn.setup's workingsets task

- org.eclipse.mylyn.releng/oomph/Mylyn.setup
I did not include the APIBaselineFromTargetTask in the last commit so the Baseline was not really set.
> 127: fix Baseline setup in Mylyn.setup

- mylyn.builds/org.eclipse.mylyn.hudson.core/META-INF/MANIFEST.MF
- mylyn.commons/org.eclipse.mylyn.commons.sdk.util/META-INF/MANIFEST.MF
- mylyn.commons/org.eclipse.mylyn.commons.tck-feature/feature.xml
- mylyn.commons/org.eclipse.mylyn.commons.ui/META-INF/MANIFEST.MF
- mylyn.context/org.eclipse.mylyn.context.tasks.tests/META-INF/MANIFEST.MF
- mylyn.context/org.eclipse.mylyn.context.tasks.ui/META-INF/MANIFEST.MF
- mylyn.reviews/org.eclipse.mylyn.gerrit.core/META-INF/MANIFEST.MF
- mylyn.reviews/org.eclipse.mylyn.gerrit.tests/META-INF/MANIFEST.MF
- mylyn.reviews/org.eclipse.mylyn.gerrit.tests/src/org/eclipse/mylyn/internal/gerrit/core/remote/GerritReviewRemoteFactoryJUnit3Test.java
- mylyn.reviews/org.eclipse.mylyn.gerrit.ui/META-INF/MANIFEST.MF
- mylyn.reviews/org.eclipse.mylyn.reviews.core/META-INF/MANIFEST.MF
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.ui/META-INF/MANIFEST.MF
- mylyn.tasks/connectors/trac/org.eclipse.mylyn.trac.core.tests/META-INF/MANIFEST.MF
- mylyn.tasks/connectors/trac/org.eclipse.mylyn.trac.ui.tests/META-INF/MANIFEST.MF
- mylyn.tasks/org.eclipse.mylyn.tasks.core/META-INF/MANIFEST.MF
- mylyn.tasks/org.eclipse.mylyn.tasks.tests/META-INF/MANIFEST.MF
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/META-INF/MANIFEST.MF
- mylyn.versions/org.eclipse.mylyn.git.core/META-INF/MANIFEST.MF
- org.eclipse.mylyn-target/mylyn-e4.26.target
Fixes https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/159
> Update guava, gson, and mockito

- org.eclipse.mylyn.releng/oomph/Mylyn.setup
This is the fix for [include Website into mylyn.setup](https://github.com/eclipse-mylyn/mylyn-website/issues/4)
The Website Repository is separate installable
> include Mylyn Website in the mylyn.setup

- mylyn.commons/org.eclipse.mylyn.commons.activity-feature/feature.properties
Name and description of feature changed to reflect its content
Fixes https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/172
> [#172] Revise name of org.eclipse.mylyn.commons.activity

- mylyn.context/org.eclipse.mylyn.bugzilla.ide/META-INF/MANIFEST.MF
- mylyn.context/org.eclipse.mylyn.bugzilla.ide/plugin.xml
Add explicit `Require-Bundle`:
* org.eclipse.mylyn.bugzilla.core
* org.eclipse.mylyn.bugzilla.ui
Fixes https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/168
> [#168] Could not load repository extension with connectorKind 'bugzilla'

- mylyn.commons/org.eclipse.mylyn.discovery.ui/src/org/eclipse/mylyn/internal/discovery/ui/wizards/DiscoveryViewer.java
Move resource image resource tracking from `ConnectorDescriptorItemUi` to enclosing `DiscoveryViewer`
Fixes https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/167
> [#167] Many "Not properly disposed SWT resource" in error log

- mylyn.context/org.eclipse.mylyn.context.tasks.ui/src/org/eclipse/mylyn/internal/context/tasks/ui/editors/ContextEditorFormPage.java
fix for UI problem (issue #170)
> Actions section of Context tab in task editor too narrow #170

- mylyn.releng/org.eclipse.mylyn.parent/pom.xml
- org.eclipse.mylyn-target/mylyn-e4.28.target
Provide and use mylyn-e4.28.target with content aligned with SimRel 2023-06
> [#187] Align target content with SimRel 2023-06

- mylyn.builds/org.eclipse.mylyn.builds-feature/feature.xml
- mylyn.context/org.eclipse.mylyn.context-feature/feature.xml
- mylyn.github/org.eclipse.mylyn.github-feature/feature.xml
- mylyn.reviews/org.eclipse.mylyn.reviews.feature/feature.xml
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.feature/feature.xml
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla-feature/feature.xml
- mylyn.tasks/connectors/trac/org.eclipse.mylyn.trac-feature/feature.xml
- mylyn.tasks/org.eclipse.mylyn-feature/feature.xml
- mylyn.tasks/org.eclipse.mylyn-feature/p2.inf
- mylyn.tasks/org.eclipse.mylyn.sdk-feature/feature.xml
- mylyn.tasks/org.eclipse.mylyn.tasks.bugs/schema/support.exsd
- mylyn.tasks/org.eclipse.mylyn.tasks.ide-feature/feature.xml
- mylyn.tasks/org.eclipse.mylyn.tasks.index-feature/feature.xml
- org.eclipse.mylyn-site/category.xml
org.eclipse.mylyn_feature -> org.eclipse.mylyn.tasks.feature
> [#204] Normalize feature identifiers to simplify support

- mylyn.context/org.eclipse.mylyn.cdt-feature/build.properties
- mylyn.context/org.eclipse.mylyn.cdt-feature/feature.xml
- mylyn.context/org.eclipse.mylyn.cdt-feature/p2.inf
- mylyn.context/org.eclipse.mylyn.context.sdk-feature/feature.xml
- org.eclipse.mylyn-site/category.xml
change identifiers and provide migration during update
Fixes #206
> [#206] org.eclipse.cdt.mylyn -> org.eclipse.mylyn.cdt.feature

- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla-feature/build.properties
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla-feature/feature.xml
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla-feature/p2.inf
- mylyn.tasks/org.eclipse.mylyn.sdk-feature/feature.xml
- org.eclipse.mylyn-site/category.xml
change identifiers and provide migration during update
Fixes #208
> [#208] org.eclipse.mylyn.bugzilla_feature -> *.mylyn.bugzilla.feature

- mylyn.builds/org.eclipse.mylyn.builds-feature/build.properties
- mylyn.builds/org.eclipse.mylyn.builds-feature/feature.xml
- mylyn.builds/org.eclipse.mylyn.builds-feature/p2.inf
- mylyn.builds/org.eclipse.mylyn.builds.sdk-feature/feature.xml
- mylyn.builds/org.eclipse.mylyn.hudson-feature/feature.xml
- org.eclipse.mylyn-site/category.xml
> [#209] org.eclipse.mylyn.builds -> org.eclipse.mylyn.builds.feature

- mylyn.commons/org.eclipse.mylyn.commons-feature/build.properties
- mylyn.commons/org.eclipse.mylyn.commons-feature/feature.xml
- mylyn.commons/org.eclipse.mylyn.commons-feature/p2.inf
- mylyn.commons/org.eclipse.mylyn.commons.activity-feature/feature.xml
- mylyn.commons/org.eclipse.mylyn.commons.notifications-feature/feature.xml
- mylyn.commons/org.eclipse.mylyn.commons.repositories-feature/feature.xml
- mylyn.commons/org.eclipse.mylyn.commons.sdk-feature/feature.xml
- mylyn.tasks/org.eclipse.mylyn-feature/feature.xml
- mylyn.versions/org.eclipse.mylyn.versions-feature/feature.xml
- org.eclipse.mylyn-site/category.xml
> [#210] org.eclipse.mylyn.commons -> org.eclipse.mylyn.commons.feature

- mylyn.context/org.eclipse.mylyn.cdt-feature/feature.xml
- mylyn.context/org.eclipse.mylyn.context-feature/build.properties
- mylyn.context/org.eclipse.mylyn.context-feature/feature.xml
- mylyn.context/org.eclipse.mylyn.context-feature/p2.inf
- mylyn.context/org.eclipse.mylyn.context.sdk-feature/feature.xml
- mylyn.context/org.eclipse.mylyn.ide-feature/feature.xml
- mylyn.context/org.eclipse.mylyn.java-feature/feature.xml
- mylyn.context/org.eclipse.mylyn.team-feature/feature.xml
- org.eclipse.mylyn-site/category.xml
> [#216] org.eclipse.mylyn.context_feature -> *.mylyn.context.feature

- mylyn.builds/org.eclipse.mylyn.builds-feature/feature.xml
- mylyn.context/org.eclipse.mylyn.context.sdk-feature/feature.xml
- mylyn.context/org.eclipse.mylyn.ide-feature/feature.xml
- mylyn.context/org.eclipse.mylyn.team-feature/build.properties
- mylyn.context/org.eclipse.mylyn.team-feature/feature.xml
- mylyn.context/org.eclipse.mylyn.team-feature/p2.inf
- mylyn.egit/org.eclipse.mylyn.egit.feature/feature.xml
- org.eclipse.mylyn-site/category.xml
> [#226] org.eclipse.mylyn.team_feature -> org.eclipse.mylyn.team.feature

- org.eclipse.mylyn-site/category.xml
https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/241
> Ensure that Mylyn update site is complete

- mylyn.builds/org.eclipse.mylyn.hudson-feature/.settings/org.eclipse.core.resources.prefs
- mylyn.builds/org.eclipse.mylyn.hudson.releng/.settings/org.eclipse.core.resources.prefs
- mylyn.builds/org.eclipse.mylyn.hudson.tests/.settings/org.eclipse.core.resources.prefs
- mylyn.builds/org.eclipse.mylyn.hudson.tests/testdata/org.eclipse.mylyn.builds.sample.ant/.settings/org.eclipse.core.resources.prefs
- mylyn.builds/org.eclipse.mylyn.hudson.tests/testdata/org.eclipse.mylyn.builds.sample.mvn.reactor/.settings/org.eclipse.core.resources.prefs
- mylyn.builds/org.eclipse.mylyn.hudson.tests/testdata/org.eclipse.mylyn.builds.sample.mvn/.settings/org.eclipse.core.resources.prefs
- mylyn.builds/org.eclipse.mylyn.hudson.ui/.settings/org.eclipse.core.resources.prefs
Hudson files keep coming back like zombies
> Hudson cleanup #257

- mylyn.commons/org.eclipse.mylyn.commons.core/src/org/eclipse/mylyn/commons/core/HtmlStreamTokenizer.java
- mylyn.commons/org.eclipse.mylyn.commons.core/src/org/eclipse/mylyn/commons/core/XmlMemento.java
- mylyn.commons/org.eclipse.mylyn.commons.net/src/org/eclipse/mylyn/commons/net/HtmlStreamTokenizer.java
- mylyn.commons/org.eclipse.mylyn.monitor.core/src/org/eclipse/mylyn/internal/monitor/core/collection/PercentUsageComparator.java
- mylyn.commons/org.eclipse.mylyn.monitor.core/src/org/eclipse/mylyn/monitor/core/InteractionEvent.java
- mylyn.reviews/org.eclipse.mylyn.gerrit.dashboard.ui/src/org/eclipse/mylyn/gerrit/dashboard/ui/internal/model/ReviewTableSorter.java
- mylyn.reviews/org.eclipse.mylyn.reviews.core/src/org/eclipse/mylyn/reviews/internal/core/model/ApprovalValueMap.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.core/src/org/eclipse/mylyn/internal/bugzilla/core/BugzillaTaskDataHandler.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.core/src/org/eclipse/mylyn/internal/bugzilla/core/SaxMultiBugReportContentHandler.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.core/src/org/eclipse/mylyn/internal/bugzilla/core/service/BugzillaXmlRpcClient.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/core/BugzillaXmlRpcClientTest.java
- mylyn.tasks/connectors/trac/org.eclipse.mylyn.trac.tests/src/org/eclipse/mylyn/trac/tests/client/TracXmlRpcTest.java
- mylyn.tasks/org.eclipse.mylyn.tasks.core/src/org/eclipse/mylyn/internal/tasks/core/TaskActivityManager.java
- mylyn.tasks/org.eclipse.mylyn.tasks.core/src/org/eclipse/mylyn/tasks/core/TaskRepository.java
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/TaskListBackupManager.java
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/editors/RichTextEditor.java
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/util/TaskAttachmentPropertyTester.java
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/util/TaskPropertyTester.java
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/util/TaskRepositoryPropertyTester.java
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/views/TaskListView.java
- mylyn.versions/org.eclipse.mylyn.subclipse.core/src/org/eclipse/mylyn/internal/subclipse/core/SubclipseConnector.java
Replaced all occurences of ```Boolean(boolean)``` with
```valueOf(boolean)```
> [#254] java.lang.Boolean constructor is deprecated

- mylyn.commons/org.eclipse.mylyn.commons.sdk.util/META-INF/MANIFEST.MF
- mylyn.commons/org.eclipse.mylyn.commons.ui/META-INF/MANIFEST.MF
- mylyn.commons/org.eclipse.mylyn.commons.ui/src/org/eclipse/mylyn/commons/ui/TableColumnDescriptorDialog.java
- mylyn.context/org.eclipse.mylyn.context.tasks.tests/META-INF/MANIFEST.MF
- mylyn.context/org.eclipse.mylyn.context.tasks.ui/META-INF/MANIFEST.MF
- mylyn.reviews/org.eclipse.mylyn.gerrit.core/META-INF/MANIFEST.MF
- mylyn.reviews/org.eclipse.mylyn.gerrit.tests/META-INF/MANIFEST.MF
- mylyn.reviews/org.eclipse.mylyn.gerrit.ui.tests/META-INF/MANIFEST.MF
- mylyn.reviews/org.eclipse.mylyn.gerrit.ui/META-INF/MANIFEST.MF
- mylyn.reviews/org.eclipse.mylyn.reviews.core/META-INF/MANIFEST.MF
- mylyn.reviews/org.eclipse.mylyn.reviews.ui.tests/META-INF/MANIFEST.MF
- mylyn.reviews/org.eclipse.mylyn.reviews.ui/META-INF/MANIFEST.MF
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.core.tests/META-INF/MANIFEST.MF
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.core/META-INF/MANIFEST.MF
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.tests/META-INF/MANIFEST.MF
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.ui/META-INF/MANIFEST.MF
- mylyn.tasks/org.eclipse.mylyn.tasks.core.tests/META-INF/MANIFEST.MF
- mylyn.tasks/org.eclipse.mylyn.tasks.core/META-INF/MANIFEST.MF
- mylyn.tasks/org.eclipse.mylyn.tasks.tests/META-INF/MANIFEST.MF
- mylyn.versions/org.eclipse.mylyn.git.core/META-INF/MANIFEST.MF
- org.eclipse.mylyn-site/category.xml
Rework guava access from `Require-Bundle` to `Import-Package`
> [#250] Rework 3rd party libs dependencies

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
Switch from `oomph` to `orbit`
> [#270]: Align target with SimRel 2023-09

- mylyn.builds/org.eclipse.mylyn.jenkins.tests/src/org/eclipse/mylyn/jenkins/tests/AllJenkinsTests.java
Disable
* JenkinsClientTest
* JenkinsIntegrationTest
Fixes #276
> [#276] Disable access to mylyn.org for jenkins tests

- mylyn.builds/org.eclipse.mylyn.jenkins.tests/src/org/eclipse/mylyn/jenkins/tests/AllJenkinsTests.java
Enable
* JenkinsClientTest
* JenkinsIntegrationTest
> [#276] Re-enable access to mylyn.org for jenkins tests

- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/META-INF/MANIFEST.MF
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/gitlab/core/GitlabConfiguration.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/gitlab/core/GitlabCoreActivator.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabJSonArrayOperation.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabRestClient.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabTaskSchema.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.feature/feature.properties
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.ui/src/org/eclipse/mylyn/internal/gitlab/ui/GitlabRepositorySettingsPage.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.ui/src/org/eclipse/mylyn/internal/gitlab/ui/GitlabSearchQueryPageSchema.java
With personalAccessToken support we now can use https://gitlab.eclipse.org.
@wimjongman @ruspl-afed do you want to do a review or should I commit direct to the main branch?
> add milestone, labels and personalAccessToken #37

- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.ui/src/org/eclipse/mylyn/internal/gitlab/ui/GitlabTaskEditorCommentPart.java
- mylyn.tasks/org.eclipse.mylyn.tasks.tests/plugin.xml
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/editors/TaskEditorCommentPart.java
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/editors/TaskEditorFindSupport.java
I rework the classes and now most fields are private again. I also introduce some new protected Methods so that we now can subclass TaskEditorCommentPart.
> Refactor TaskEditorCommentPart, CommentGroupViewer, CommentViewer #266

- mylyn.github/org.eclipse.mylyn.github.core/src/org/eclipse/mylyn/internal/github/core/GitHub.java
- mylyn.github/org.eclipse.mylyn.github.core/src/org/eclipse/mylyn/internal/github/core/gist/GistTaskDataHandler.java
- mylyn.github/org.eclipse.mylyn.github.core/src/org/eclipse/mylyn/internal/github/core/issue/IssueConnector.java
- mylyn.github/org.eclipse.mylyn.github.core/src/org/eclipse/mylyn/internal/github/core/pr/PullRequestConnector.java
- mylyn.github/org.eclipse.mylyn.github.ui/src/org/eclipse/mylyn/internal/github/ui/HttpRepositorySettingsPage.java
- mylyn.github/org.eclipse.mylyn.github.ui/src/org/eclipse/mylyn/internal/github/ui/TaskRepositoryImportWizard.java
- mylyn.github/org.eclipse.mylyn.github.ui/src/org/eclipse/mylyn/internal/github/ui/gist/GistRepositorySettingsPage.java
- mylyn.github/org.eclipse.mylyn.github.ui/src/org/eclipse/mylyn/internal/github/ui/issue/IssueRepositorySettingsPage.java
- mylyn.github/org.eclipse.mylyn.github.ui/src/org/eclipse/mylyn/internal/github/ui/issue/IssueTaskEditorPage.java
- mylyn.github/org.eclipse.mylyn.github.ui/src/org/eclipse/mylyn/internal/github/ui/pr/PullRequestRepositorySettingsPage.java
- mylyn.tasks/org.eclipse.mylyn.tasks.core/src/org/eclipse/mylyn/internal/tasks/core/IRepositoryConstants.java
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/wizards/Messages.java
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/wizards/messages.properties
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/tasks/ui/wizards/AbstractRepositorySettingsPage.java
Move GitHub "kludge" code for token authentication option into the base repository code.
> Add token authentication option to base repository code #62

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
Task-Url: https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/issues/303
> Move simrel/maven-{bnd,osgi} to simrel/orbit-aggregation/2023-12 #303

- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/gitlab/core/Duration.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/gitlab/core/GitlabConfiguration.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/gitlab/core/GitlabCoreActivator.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/gitlab/core/GitlabException.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabActivityStyle.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabJSonArrayOperation.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabNewTaskSchema.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabOperation.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabPostOperation.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabPutOperation.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabRepositoryConnector.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabRestClient.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabTaskAttributeMapper.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabTaskDataHandler.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabTaskSchema.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.ui/src/org/eclipse/mylyn/gitlab/ui/GitlabUiActivator.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.ui/src/org/eclipse/mylyn/internal/gitlab/ui/GitlabConnectorUI.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.ui/src/org/eclipse/mylyn/internal/gitlab/ui/GitlabQuerySchemaPage.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.ui/src/org/eclipse/mylyn/internal/gitlab/ui/GitlabQueryTypeWizardPage.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.ui/src/org/eclipse/mylyn/internal/gitlab/ui/GitlabRepositorySettingsPage.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.ui/src/org/eclipse/mylyn/internal/gitlab/ui/GitlabSearchQueryPageSchema.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.ui/src/org/eclipse/mylyn/internal/gitlab/ui/GitlabTaskEditorCommentPart.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.ui/src/org/eclipse/mylyn/internal/gitlab/ui/GitlabTaskEditorPage.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.ui/src/org/eclipse/mylyn/internal/gitlab/ui/GitlabTaskEditorPageFactory.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.ui/src/org/eclipse/mylyn/internal/gitlab/ui/GitlabTaskEditorSummaryPart.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.ui/src/org/eclipse/mylyn/internal/gitlab/ui/TaskEditorActivityPart.java
adjust the Source to the Codestyle from #200
> [#37] Gitlab Connector Cleanup Code Style configuration for Java 17

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
Align all repository location with what we have at SImRel
> Adapt target for 2023-12 RC1 state of SimRel

- mylyn.docs/epub/ui/pom.xml
- mylyn.docs/pom.xml
- mylyn.docs/wikitext/ui/pom.xml
- mylyn.releng/org.eclipse.mylyn.parent/pom.xml
This configuration is gone in 4.x
> Remove tycho old configs

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
> Update to latest SimRel 2023-12 contributions:

- mylyn.tasks/org.eclipse.mylyn.tasks.tests/src/org/eclipse/mylyn/tasks/tests/TaskDataStoreTest.java
> [#329] Reduce amount of cycles in TaskDataStoreTest

- mylyn.docs/.project
- mylyn.docs/wikitext/core/.project
- mylyn.docs/wikitext/ui/.project
- mylyn.docs/wikitext/ui/org.eclipse.mylyn.wikitext.asciidoc.ui/.classpath
- mylyn.docs/wikitext/ui/org.eclipse.mylyn.wikitext.asciidoc.ui/.externalToolBuilders/org.eclipse.pde.api.tools.apiAnalysisBuilder.launch
- mylyn.docs/wikitext/ui/org.eclipse.mylyn.wikitext.asciidoc.ui/.project
- mylyn.docs/wikitext/ui/org.eclipse.mylyn.wikitext.markdown.ui/.project
- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
- org.eclipse.mylyn.releng/oomph/Mylyn.setup
Wit this we will reduce the number of errors in the problems view.
This is done with changes in the .project definitions and changes in mylyn.setup.
Sometimes I need to do a Projects Clean... to bring the errors to zero
So if you use the Eclipse installer and select Mylyn with the MylynDocs-Setup-Test stream, you should see fewer errors in the problem view than in the main stream.
> [#315] mylyn.setup corrections

- mylyn.docs/epub/ui/org.eclipse.mylyn.docs.epub.help/pom.xml
- mylyn.docs/target-platform/mylyn-docs.target
- mylyn.docs/wikitext/ui/org.eclipse.mylyn.wikitext.osgi/META-INF/MANIFEST.MF
- mylyn.docs/wikitext/ui/org.eclipse.mylyn.wikitext.ui/META-INF/MANIFEST.MF
* switch pom.xml to Guava 33.0.0.jre
* switch MANIFEST.MF to Guava [33.0.0,34.0.0)
Fixes #348
> [#348] Switch Mylyn Docs to Guava 33.0.0.jre

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
> [#350] Prepare contribution for SimRel 2024-03 M1

- org.eclipse.mylyn-site/category.xml
> [#358] Contribute federated Mylyn (+Docs) to SimRel

- mylyn.versions/org.eclipse.mylyn.git.core/src/org/eclipse/mylyn/internal/git/core/GitArtifact.java
- mylyn.versions/org.eclipse.mylyn.git.core/src/org/eclipse/mylyn/internal/git/core/GitConnector.java
- mylyn.versions/org.eclipse.mylyn.git.core/src/org/eclipse/mylyn/internal/git/core/GitRepository.java
- mylyn.versions/org.eclipse.mylyn.git.core/src/org/eclipse/mylyn/internal/git/core/LazyChangeSet.java
- mylyn.versions/org.eclipse.mylyn.git.ui/src/org/eclipse/mylyn/internal/git/ui/GetChangeSetDialog.java
- mylyn.versions/org.eclipse.mylyn.versions.core/src/org/eclipse/mylyn/versions/core/Change.java
- mylyn.versions/org.eclipse.mylyn.versions.core/src/org/eclipse/mylyn/versions/core/ChangeSet.java
- mylyn.versions/org.eclipse.mylyn.versions.core/src/org/eclipse/mylyn/versions/core/ProjectSetConverter.java
- mylyn.versions/org.eclipse.mylyn.versions.core/src/org/eclipse/mylyn/versions/core/ScmArtifact.java
- mylyn.versions/org.eclipse.mylyn.versions.core/src/org/eclipse/mylyn/versions/core/ScmCore.java
- mylyn.versions/org.eclipse.mylyn.versions.core/src/org/eclipse/mylyn/versions/core/ScmRepository.java
- mylyn.versions/org.eclipse.mylyn.versions.core/src/org/eclipse/mylyn/versions/core/ScmUser.java
- mylyn.versions/org.eclipse.mylyn.versions.core/src/org/eclipse/mylyn/versions/core/spi/ScmInfoAttributes.java
- mylyn.versions/org.eclipse.mylyn.versions.core/src/org/eclipse/mylyn/versions/core/spi/ScmResourceArtifact.java
- mylyn.versions/org.eclipse.mylyn.versions.core/src/org/eclipse/mylyn/versions/core/spi/ScmResourceUtils.java
- mylyn.versions/org.eclipse.mylyn.versions.tests/src/org/eclipse/mylyn/versions/tests/support/MockRepositoryProvider.java
- mylyn.versions/org.eclipse.mylyn.versions.ui/src/org/eclipse/mylyn/versions/ui/ScmUi.java
- mylyn.versions/org.eclipse.mylyn.versions.ui/src/org/eclipse/mylyn/versions/ui/spi/ScmConnectorUi.java
Task-Url: https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/380
> Clean Up: Builds #380

- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabRepositoryConnector.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabRestClient.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabTaskAttributeMapper.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.ui/src/org/eclipse/mylyn/internal/gitlab/ui/GitlabQuerySchemaPage.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.ui/src/org/eclipse/mylyn/internal/gitlab/ui/GitlabRepositorySettingsPage.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.ui/src/org/eclipse/mylyn/internal/gitlab/ui/TaskEditorActivityPart.java
Task-Url: https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/404
> Clean up- GItlab Connector #404

- mylyn.egit/org.eclipse.mylyn.egit.ui.tests/src/org/eclipse/mylyn/egit/internal/ui/tests/CommitHyperlinkDetectorTest.java
Task-Url: https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/416
> 416: Resolve "light" warnings for Mylyn EGit

- mylyn.commons/org.eclipse.mylyn.commons.ui/.settings/.api_filters
add compatibility problem filter
> [#411] Resolve "light" warnings for Mylyn Commons

- mylyn.context/org.eclipse.mylyn.context.ui/.settings/.api_filters
* add compatibility problem filter
> [#417] Resolve "light" warnings for Mylyn Context

- SECURITY.md
> [#448] add SECURITY root file

- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.ant.tests/src/test/java/org/eclipse/mylyn/wikitext/ant/internal/tests/AbstractTestAntTask.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.asciidoc.tests/src/test/java/org/eclipse/mylyn/internal/wikitext/asciidoc/tests/AsciiDocDocumentBuilderTest.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.asciidoc.tests/src/test/java/org/eclipse/mylyn/internal/wikitext/asciidoc/tests/AsciiDocLanguageListTest.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.asciidoc.tests/src/test/java/org/eclipse/mylyn/internal/wikitext/asciidoc/tests/AsciiDocLanguageSupportTest.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.asciidoc.tests/src/test/java/org/eclipse/mylyn/internal/wikitext/asciidoc/tests/AsciiDocLanguageTableTest.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.asciidoc.tests/src/test/java/org/eclipse/mylyn/internal/wikitext/asciidoc/tests/AsciiDocLanguageTestBase.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.asciidoc.tests/src/test/java/org/eclipse/mylyn/internal/wikitext/asciidoc/tests/AsciiDocLanguageWithConfigurationIntegrationTest.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.commonmark.tests/src/test/java/org/eclipse/mylyn/wikitext/commonmark/internal/CommonMarkAsserts.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.commonmark.tests/src/test/java/org/eclipse/mylyn/wikitext/commonmark/internal/LineTest.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.commonmark.tests/src/test/java/org/eclipse/mylyn/wikitext/commonmark/internal/SimpleLocatorTest.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.commonmark.tests/src/test/java/org/eclipse/mylyn/wikitext/commonmark/internal/SourceBlocksTest.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.commonmark.tests/src/test/java/org/eclipse/mylyn/wikitext/commonmark/internal/inlines/AbstractSourceSpanTest.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.commonmark.tests/src/test/java/org/eclipse/mylyn/wikitext/commonmark/internal/inlines/InlineTest.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.commonmark.tests/src/test/java/org/eclipse/mylyn/wikitext/commonmark/internal/spec/tests/CommonMarkSpecTest.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.commonmark.tests/src/test/java/org/eclipse/mylyn/wikitext/commonmark/internal/spec/tests/SimplifiedHtmlDocumentBuilder.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.commonmark.tests/src/test/java/org/eclipse/mylyn/wikitext/commonmark/tests/CommonMarkLanguageDocumentOffsetsTest.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.commonmark.tests/src/test/java/org/eclipse/mylyn/wikitext/commonmark/tests/CommonMarkLanguageTest.java
Add `@SuppressWarnings("restriction")` for tests
to be continued...
> [#423] Resolve "light" warnings for Mylyn Docs

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
* Platform
* EMF
* ECF
* CDT
* Orbit
Fixes #457
> [#457] Prepare target for 2024-03 RC2

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
Fix target definition for Platform 4.31
> [#469] Prepare releng for 4.3.0

- .mvn/extensions.xml
- mylyn.docs/pom.xml
- mylyn.releng/org.eclipse.mylyn.parent/pom.xml
* switch from 4.0.4 to 4.0.6
* resolve version warnings
> [#462] Switch to Tycho 4.0.6

- mylyn.builds/org.eclipse.mylyn.jenkins.tests/src/org/eclipse/mylyn/jenkins/tests/AllJenkinsTests.java
- mylyn.commons/org.eclipse.mylyn.commons.notifications.tests/src/org/eclipse/mylyn/commons/notifications/tests/AllNotificationsTests.java
- mylyn.commons/org.eclipse.mylyn.commons.notifications.tests/src/org/eclipse/mylyn/commons/notifications/tests/core/NotificationEnvironmentTest.java
- mylyn.commons/org.eclipse.mylyn.commons.notifications.tests/src/org/eclipse/mylyn/commons/notifications/tests/feed/ServiceMessageManagerTest.java
- mylyn.commons/org.eclipse.mylyn.commons.repositories.http.tests/src/org/eclipse/mylyn/commons/repositories/http/tests/CommonHttpClientTest.java
- mylyn.commons/org.eclipse.mylyn.commons.repositories.http.tests/src/org/eclipse/mylyn/commons/repositories/http/tests/CommonHttpResponseTest.java
- mylyn.commons/org.eclipse.mylyn.commons.tests/src/org/eclipse/mylyn/commons/tests/AllCommonsTests.java
- mylyn.commons/org.eclipse.mylyn.commons.tests/src/org/eclipse/mylyn/commons/tests/net/CommonHttpMethod3Test.java
- mylyn.commons/org.eclipse.mylyn.commons.tests/src/org/eclipse/mylyn/commons/tests/net/WebUtilTest.java
- mylyn.commons/org.eclipse.mylyn.commons.tests/src/org/eclipse/mylyn/commons/tests/workbench/browser/BrowserUtilTest.java
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.core.tests/src/org/eclipse/mylyn/bugzilla/rest/core/tests/BugzillaRestClientTest.java
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.core.tests/src/org/eclipse/mylyn/bugzilla/rest/core/tests/BugzillaRestConfigurationTest.java
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.core.tests/src/org/eclipse/mylyn/bugzilla/rest/core/tests/BugzillaRestConnectorTest.java
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.core.tests/src/org/eclipse/mylyn/bugzilla/rest/core/tests/BugzillaRestFlagMapperTest.java
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.tests/src/org/eclipse/mylyn/bugzilla/rest/tests/tck/AbstractRepositoryConnectorTest.java
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.tests/src/org/eclipse/mylyn/bugzilla/rest/tests/tck/ValidationTest.java
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.tests/src/org/eclipse/mylyn/bugzilla/rest/tests/tck/ui/AbstractRepositorySettingsPageTest.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/AllBugzillaTests.java
- mylyn.tasks/org.eclipse.mylyn.tasks.tests/src/org/eclipse/mylyn/tasks/tests/core/SynchronizeTasksJobTest.java
- mylyn.tasks/org.eclipse.mylyn.tasks.ui.tests/src/org/eclipse/mylyn/internal/tasks/ui/BrandManagerTest.java
Task-Url: https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/504
> Disable integration tests that need mylyn.org #504

- mylyn.tasks/org.eclipse.mylyn.tasks.ui.tests/src/org/eclipse/mylyn/internal/tasks/ui/BrandManagerTest.java
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/META-INF/MANIFEST.MF
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/BrandManager.java
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/migrator/ConnectorMigrator.java
Replaced guavas HashBasedTable #307 
One down,  two to go
> 307 replace guava hashbasedtable

- mylyn.tasks/org.eclipse.mylyn.tasks.ui/META-INF/MANIFEST.MF
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/editors/TaskEditorExtensions.java
- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
Replace guavas MediaType
two down, one to go
> 306 replace guava mediatype

- mylyn.reviews/org.eclipse.mylyn.gerrit.core/META-INF/MANIFEST.MF
- mylyn.reviews/org.eclipse.mylyn.gerrit.core/src/org/eclipse/mylyn/internal/gerrit/core/client/GerritClient212.java
Replace guava TypeToken with gson TypeToken
Task-Url: https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/305
> Remove guava TypeToken #305

- org.eclipse.mylyn.releng/multipass/mylyn_setup.yml
- org.eclipse.mylyn.releng/multipass/roles/dockerhost/tasks/main.yml
- org.eclipse.mylyn.releng/multipass/roles/gitlab/files/doInit.sh
- org.eclipse.mylyn.releng/multipass/roles/gitlab/files/initialSetup.rb
- org.eclipse.mylyn.releng/multipass/roles/mylyn_idx/tasks/main.yml
Sorry, I forgot to commit the changes needed for Ubuntu 24.04 LTS
> commit some changes for gitlab setup, python docker and docker compose

- .mvn/extensions.xml
- mylyn.docs/pom.xml
- mylyn.releng/org.eclipse.mylyn.parent/pom.xml
* switch extensions
* switch parent pom
> [#535] Switch to Tycho 4.8.0

- org.eclipse.mylyn.releng/multipass/mylyn_setup.yml
- org.eclipse.mylyn.releng/multipass/roles/bugzilla/tasks/build_start.yml
- org.eclipse.mylyn.releng/multipass/roles/gitlab/tasks/main.yml
- org.eclipse.mylyn.releng/multipass/roles/jenkins/tasks/build_start.yml
Sorry this was a type of none Mac builds.
> use ce Version in gitlabImageName

- mylyn.docs/wikitext/ui/org.eclipse.mylyn.wikitext.asciidoc.ui/.project
- mylyn.docs/wikitext/ui/org.eclipse.mylyn.wikitext.markdown.ui/.project
- mylyn.github/org.eclipse.mylyn.github.doc/pom.xml
- org.eclipse.mylyn.releng/launcher/mylyn install.launch
- org.eclipse.mylyn.releng/oomph/Mylyn.setup
we have 6 errors in the workspace for a new instance.
This commit fix the errors using more oomph setup tasks.
> fix the workspace errors for a new clean instance

- Jenkinsfile
Add more time to the timeout value as we are getting too close to the previous value.
> [#544] set timeout to 80 Minutes

- org.eclipse.mylyn.releng/oomph/Mylyn.setup
1. remove the not working .github repository setup
2. add all Doc projects to the Doc Workingset
> small oomph setup fixes

- .github/workflows/licensecheck.yml
To fix path to licensecheck gh action.
> Fix dash project github org

- mylyn.context/org.eclipse.mylyn.context.sdk.java/src/org/eclipse/mylyn/context/sdk/java/WorkspaceSetupHelper.java
- mylyn.context/org.eclipse.mylyn.context.tests/src/org/eclipse/mylyn/context/tests/support/ContextTestUtil.java
PDE was merged into PluginProject
https://github.com/eclipse-pde/eclipse.pde/commit/a37e0a10d8e3c3fbeb3805e5f7cf8391dc04855c
Task-Url: https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/578
> org.eclipse.pde.internal.core.natures.PDE missing #578

- mylyn.context/org.eclipse.mylyn.context.sdk.java/src/org/eclipse/mylyn/context/sdk/java/WorkspaceSetupHelper.java
- mylyn.context/org.eclipse.mylyn.context.tests/src/org/eclipse/mylyn/context/tests/support/ContextTestUtil.java
- Avoid PluginProject.NATURE because that was very recently added there.
https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/578
> Use IBundleProjectDescription.PLUGIN_NATURE

- org.eclipse.mylyn.releng/multipass/roles/jenkins/tasks/build_start.yml
The loop did not realy work so we need to fix it
> fix: Support for multiple Jenkins instances

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
Update target for 2024-09 RC1
* EMF
* ECF
* CDT
> [#607] Prepare Mylyn contribution for 2024-09

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
* align target with SimRel 2024-12
Fixes #611
> [#611] Prepare releng to 4.5.0

- mylyn.tasks/org.eclipse.mylyn.tasks.ui.tests/META-INF/MANIFEST.MF
- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
* Platform
* EGit
* EMF
Fixes #635
> [#635] Prepare contribution for Eclipse SimRel 2024-12 M3

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
> [#640] Prepare contribution for Eclipse SimRel 2024-12 RC1

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
> [#642] Prepare contribution for Eclipse SimRel 2024-12 RC2

- Jenkinsfile
- Fred Gurr recommended changing to ubuntu for other projects of mine.
- Enhance the build description to show details on the ci instance.
> Use ubuntu instead of centos

- Jenkinsfile
- mylyn.tasks/org.eclipse.mylyn.tasks.core/src/org/eclipse/mylyn/internal/tasks/core/data/TaskDataExternalizer.java
- mylyn.tasks/org.eclipse.mylyn.tasks.index.core/META-INF/MANIFEST.MF
- mylyn.tasks/org.eclipse.mylyn.tasks.index.core/src/org/eclipse/mylyn/internal/tasks/index/core/TaskListIndex.java
- mylyn.tasks/org.eclipse.mylyn.tasks.index.tests/META-INF/MANIFEST.MF
- mylyn.tasks/org.eclipse.mylyn.tasks.tests/src/org/eclipse/mylyn/tasks/tests/data/TaskDataExternalizerTest.java
- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
- Update the target platform to use 4.35-I-builds and 2025-03 orbit.
- Because there is API breakage, require minimally lucene 10.
> Changes to support lucene 10.0.0

- mylyn.releng/org.eclipse.mylyn.parent/pom.xml
- org.eclipse.mylyn-site/pom.xml
- Update the justj.p2.manager to use Java 21 because eventually it will need Java 21.
> Update to Tycho 4.0.10

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
* update Platform
* update EMF
Fixes #662
> [#662] Prepare to 4.6.0 M1

- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.tracwiki/src/main/java/org/eclipse/mylyn/wikitext/tracwiki/TracWikiLanguage.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core.test/src/org/eclipse/mylyn/gitlab/core/test/RestfulGitlabClientTest.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core.test/testdata/configuration.json
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core.test/testdata/getGroups.json
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core.test/testdata/getUsers.json
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core.test/testdata/getUsers_alert-bot_support-bot.json
- org.eclipse.mylyn.releng/multipass/mylyn_setup.yml
in #658 we got errors because gitlab was updated to 17.4.0but not the testdata.
With this change we go to Version 17.7.0 and adjust the Testdata.
Now the tests also work when you change the localhost.test.server to an other value
> Update Gitlab Test Server to 17.7.0 #658

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
> [#670] Prepare to 4.6.0 M2

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
* Platform
* EGit
* CDT
* 
Fixes #675
> [#675] Prepare to 4.6.0 M3

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
* EMF
* Platform
* CDT
Fixes #679
> [#679] Prepare to 4.6.0 RC1

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
* Platform
* EGit
* CDT
Fixes #682
> [#682] Prepare 4.6 RC2 contribution

- mylyn.releng/org.eclipse.mylyn.parent/pom.xml
- pom.xml
One less maven module to build.
> Point to target as a file

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
* EMF
* Platform
* EGit
* CDT
* Orbit
> [#703] Prepare to 4.7.0 M1

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
* EMF
* ECF
* Platform
* EGit
* CDT
> [#713] Prepare to 4.7.0 M2

- Jenkinsfile
Keep running with test failures and errors
> Fix main pipeline

- Jenkinsfile
- mylyn.releng/org.eclipse.mylyn.parent/pom.xml
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core.test/src/org/eclipse/mylyn/gitlab/core/test/RestfulGitlabClientTest.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core.test/src/org/eclipse/mylyn/internal/gitlab/core/GitlabRestClientTest.java
- org.eclipse.mylyn.tests/pom.xml
Increase Gitlab test types and methods visibility
> Fix main pipeline attempt 2

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
> [#720] Prepare to 4.7.0 M3

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
> [#729] Prepare 4.7.0 RC2 contribution

- mylyn.context/org.eclipse.mylyn.cdt-feature/feature.xml
- mylyn.github/org.eclipse.mylyn.github-feature/feature.xml
- mylyn.github/org.eclipse.mylyn.github.core/META-INF/MANIFEST.MF
- mylyn.github/org.eclipse.mylyn.github.doc/META-INF/MANIFEST.MF
- mylyn.github/org.eclipse.mylyn.github.doc/pom.xml
- mylyn.github/org.eclipse.mylyn.github.tests/META-INF/MANIFEST.MF
- mylyn.github/org.eclipse.mylyn.github.ui/META-INF/MANIFEST.MF
- bump versions for separately versioned plugins and features
> [#739] Prepare releng for 4.8.0 development cycle

- mylyn.builds/org.eclipse.mylyn.jenkins.tests/src/org/eclipse/mylyn/jenkins/tests/client/JenkinsClientTest.java
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.core.tests/src/org/eclipse/mylyn/bugzilla/rest/core/tests/BugzillaRestClientTest.java
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.core.tests/src/org/eclipse/mylyn/bugzilla/rest/core/tests/BugzillaRestConfigurationTest.java
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.core.tests/src/org/eclipse/mylyn/bugzilla/rest/core/tests/BugzillaRestConnectorTest.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/BugzillaAttachmentHandlerTest.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/BugzillaRepositoryConnectorTest.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/BugzillaSearchTest.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/BugzillaTaskDataHandlerTest.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/EncodingTest.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/RepositoryReportFactoryTest.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/core/BugzillaClientTest.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/core/BugzillaCustomFieldsTest.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/core/BugzillaFlagsTest.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/core/BugzillaRepositoryConnectorStandaloneTest.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/core/BugzillaTaskCompletionTest.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/core/BugzillaXmlRpcClientTest.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/ui/BugzillaRepositorySettingsPageTest.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/ui/BugzillaSearchPageTest.java
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/ui/BugzillaTaskEditorTest.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core.test/src/org/eclipse/mylyn/gitlab/core/test/RestfulGitlabClientTest.java
- org.eclipse.mylyn-target/org.eclipse.mylyn.baseline.target
* align target with 2025-09 M1
> [#748] Prepare 4.8.0 M1 contribution

- .github/workflows/ci.yml
- .github/workflows/unit-tests.yml
* unit-tests for different platforms
* unit-test result publishing
> [#756] Reuse platform CI

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
* EMF
* ECF
* Platform
* EGit
* CDT
> [#767] Prepare 4.8.0 M2 contribution

- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.asciidoc/META-INF/MANIFEST.MF
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.asciidoc/src/main/java/org/eclipse/mylyn/wikitext/asciidoc/internal/util/LanguageSupport.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.confluence/META-INF/MANIFEST.MF
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.confluence/src/main/java/org/eclipse/mylyn/wikitext/confluence/internal/ConfluenceDocumentBuilder.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.confluence/src/main/java/org/eclipse/mylyn/wikitext/confluence/internal/block/TableBlock.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.html/META-INF/MANIFEST.MF
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.html/src/main/java/org/eclipse/mylyn/wikitext/html/internal/SpanStrategies.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.maven/pom.xml
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.textile.tests/META-INF/MANIFEST.MF
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.textile.tests/src/test/java/org/eclipse/mylyn/wikitext/textile/internal/tests/TextileDocumentBuilderEntityReferenceTest.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.textile/META-INF/MANIFEST.MF
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.textile/src/main/java/org/eclipse/mylyn/wikitext/textile/internal/block/TableBlock.java
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext/src/main/java/org/eclipse/mylyn/wikitext/parser/builder/HtmlEntities.java
- mylyn.docs/wikitext/core/pom.xml
- mylyn.docs/wikitext/ui/org.eclipse.mylyn.wikitext.help.ui/pom.xml
- org.eclipse.mylyn-site/category.xml
- org.eclipse.mylyn-target/org.eclipse.mylyn.baseline.target
- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
> Remove last vestiges of guava #575

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
> [#862] Prepare 4.8.0 RC1 contribution

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
> [#865] Prepare 4.8.0 RC2 contribution

- mylyn.reviews/org.eclipse.mylyn.gerrit.core/src/org/eclipse/mylyn/internal/gerrit/core/client/rest/AbandonInput.java
- mylyn.reviews/org.eclipse.mylyn.gerrit.core/src/org/eclipse/mylyn/internal/gerrit/core/client/rest/RestoreInput.java
This change is intended to prevent the cleanup from removing the unused Message field.
> add getter for field message #831
