eclipse-mylyn/org.eclipse.mylyn

- mylyn.commons/org.eclipse.mylyn.commons.identity.core/OSGI-INF/component.xml
for "!MESSAGE bundle org.eclipse.mylyn.commons.identity.core:3.26.0.qualifier (608) General problem with descriptor entry '/OSGI-INF/component.xml' "
As a Result we do not see the pictures in UserAttributeEditor
> fix: Startup Message General problem with descriptor entry

- mylyn.builds/org.eclipse.mylyn.builds.sdk-feature/feature.xml
- mylyn.builds/org.eclipse.mylyn.hudson-feature/feature.xml
- mylyn.builds/org.eclipse.mylyn.hudson.core/META-INF/MANIFEST.MF
- mylyn.commons/org.eclipse.mylyn.commons.notifications-feature/feature.xml
- mylyn.commons/org.eclipse.mylyn.commons.notifications.feed/META-INF/MANIFEST.MF
- mylyn.commons/org.eclipse.mylyn.commons.notifications.tests/META-INF/MANIFEST.MF
- mylyn.commons/org.eclipse.mylyn.commons.sdk-feature/feature.xml
- org.eclipse.mylyn-site/category.xml
Switch from `Require-Bundle` to `Import-Package`for javax.xml 
Switch from includes/requires for feature to providing in repository
> Hudson connector needs JAXB-API with Java 11+ #55

- Jenkinsfile
- mylyn.reviews/org.eclipse.mylyn.reviews.ui.tests/src/org/eclipse/mylyn/internal/reviews/ui/annotations/CommentPopupDialogTest.java
- mylyn.tasks/org.eclipse.mylyn-feature/feature.xml
- mylyn.tasks/org.eclipse.mylyn.tasks.index.core/META-INF/MANIFEST.MF
- mylyn.tasks/org.eclipse.mylyn.tasks.tests/src/org/eclipse/mylyn/tasks/tests/TasksUiUtilTest.java
- org.eclipse.mylyn-site/category.xml
With this we only use org.apache.lucene version to be less then 8.0 so we do not migrate the data and can stay with the tested 6.1 version.
To get the build work I need to switch to apache-maven-3.8.6 (from apache-maven-latest) Maven 3.9 did not work and 3.9.1 is actual not available.
> 70 org.eclipse.mylyn.tasks.activity.tests fails

- .github/workflows/licensecheck.yml
- mylyn.tasks/connectors/bugzilla/org.eclipse.mylyn.bugzilla.tests/src/org/eclipse/mylyn/bugzilla/tests/BugzillaAttachmentHandlerTest.java
- mylyn.tasks/org.eclipse.mylyn-feature/feature.xml
- mylyn.tasks/org.eclipse.mylyn.sdk-feature/feature.xml
- mylyn.tasks/org.eclipse.mylyn.tasks.index.core/META-INF/MANIFEST.MF
- mylyn.tasks/org.eclipse.mylyn.tasks.index.core/src/org/eclipse/mylyn/internal/tasks/index/core/TaskListIndex.java
- mylyn.tasks/org.eclipse.mylyn.tasks.tests/src/org/eclipse/mylyn/tasks/tests/AllTasksTests.java
- org.eclipse.mylyn-site/category.xml
- org.eclipse.mylyn-target/mylyn-e4.26.target
- org.eclipse.mylyn.tests/META-INF/MANIFEST.MF
I have changed BugzillaAttachmentHandlerTest.java and AllTasksTests.java to get no failures when running on my MacBook with maven.
Please do some tests because I only tried the following cases with eclipse 2022-06 and 2023-03
1. new instance of eclipse and create a query
2. latest released mylyn and  create a query. After this upgrade to the version with Lucene 9.5.0.
(not sure that I have tested all possible cases where we have left some entries with duplicate Date values)
> Apache Lucene update from 6.1.0 to Apache Lucene 9.5.0 (#82)

- org.eclipse.mylyn-site/category.xml
- org.eclipse.mylyn-target/mylyn-e4.26.target
xmlrpc.server requires a logging < 1.2.0
This resolves the immediate issue in SimRel - https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/201693/comments/cf5c3a34_9e765dd6
I did a `mvn clean package` and then then added `$PWD/org.eclipse.mylyn-site/target/repository` to the simrel.aggr and validated locally.
> Add in a version of logging that is compatible

- Jenkinsfile
- org.eclipse.mylyn-site/pom.xml
Reuse JustJ's repository publishing infrastructure.
Ensure that only main branch builds are signed and promoted.
https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/116
> Support a stable repository structure for publishing builds

- org.eclipse.mylyn-site/pom.xml
I mistakenly assumed the publisher copied these images, but it does not.
> The branding images should refer to on-line images

- org.eclipse.mylyn-site/category.xml
This appears just to have various dependencies for tests
https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/131
> Remove org.eclipse.mylyn.commons.tck from the site

- mylyn.commons/org.eclipse.mylyn.commons.sdk-feature/feature.xml
- mylyn.tasks/org.eclipse.mylyn-feature/feature.xml
- mylyn.versions/org.eclipse.mylyn.versions.sdk-feature/feature.xml
- org.eclipse.mylyn-site/category.xml
- org.eclipse.mylyn-target/mylyn-e4.26.target
This is to ensure that all of Mylyn's features install with a minimal set of other update sites available.
Fixes https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/159
> Ensure that 3rd party dependencies are available in the update site

- mylyn.egit/org.eclipse.mylyn.egit.feature/build.properties
- mylyn.egit/org.eclipse.mylyn.egit.feature/p2.inf
I.e., so that org.eclipse.egit.mylyn.feature.group to can update to org.eclipse.mylyn.egit.feature.feature.group
https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/165
> Provide a p2.inf to handle the renaming of egit.mylyn to mylyn.egit

- mylyn.context/org.eclipse.mylyn.ide-feature/feature.xml
It used to be that the Mylyn IDE feature didn't really pull in any connectors, but just IDE features. However there was a log message about bugzilla as repored in #168
The current fix for #168 pulls in more of bugzilla when the ide_feature is installed.
Therefore this change is to not pull in bugzilla at all when installing IDE feature.
Fixes https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/168
> Remove bugzilla from Mylyn IDE feature

- org.eclipse.mylyn.tests/pom.xml
When running with -DskipTests=true, there are no generated reports and then trying to transform them fails.
> Don't transform surefire report when skipTests is true

- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/views/TaskListFilteredTree.java
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/views/TaskListView.java
* Obtain Image instance via ImageRegistry
* Do not expand disposed viewer
Fixes https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/186
> [#186] Exceptions when closing Task List view

- mylyn.commons/org.eclipse.mylyn.commons.sdk.util/src/org/eclipse/mylyn/commons/sdk/util/UiTestUtil.java
- mylyn.context/org.eclipse.mylyn.context.sdk.util/META-INF/MANIFEST.MF
- mylyn.context/org.eclipse.mylyn.context.sdk.util/src/org/eclipse/mylyn/context/sdk/util/AbstractResourceContextTest.java
- mylyn.context/org.eclipse.mylyn.ide.ui/META-INF/MANIFEST.MF
- mylyn.context/org.eclipse.mylyn.ide.ui/src/org/eclipse/mylyn/internal/ide/ui/IdeUiUtil.java
- mylyn.context/org.eclipse.mylyn.ide.ui/src/org/eclipse/mylyn/internal/ide/ui/actions/FocusResourceNavigatorAction.java
- mylyn.context/org.eclipse.mylyn.java.tests/META-INF/MANIFEST.MF
- mylyn.context/org.eclipse.mylyn.java.tests/src/org/eclipse/mylyn/java/tests/InterestManipulationTest.java
- mylyn.context/org.eclipse.mylyn.java.tests/src/org/eclipse/mylyn/java/tests/JavaStructureTest.java
- mylyn.context/org.eclipse.mylyn.java.tests/src/org/eclipse/mylyn/java/tests/ResourceStructureMappingTest.java
- mylyn.context/org.eclipse.mylyn.resources.tests/src/org/eclipse/mylyn/resources/tests/AbstractResourceContextTest.java
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/PlanningPerspectiveFactory.java
Switch to Project Explorer
Fixing https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/190
> [#190] Remove references to Resource Navigator

- .gitignore
- org.eclipse.mylyn-target/mylyn-e4.28.target
- org.eclipse.mylyn.releng/oomph/Mylyn.setup
The following was changed
- mylyn-e4.28.target
4.28-I-builds/I20230601-1220 no longer exists we now use 4.28/R-4.28-202306050440
- Mylyn.setup
use mylyn-e4.28.target as the target platform instead of mylyn-e4.26.target
- add .polyglot.* to gitignore
> fix some small problems for final eclipse 4.28

- mylyn.commons/org.eclipse.mylyn.commons.activity-feature/build.properties
- mylyn.commons/org.eclipse.mylyn.commons.activity-feature/feature.xml
- mylyn.commons/org.eclipse.mylyn.commons.activity-feature/p2.inf
- org.eclipse.mylyn-site/category.xml
> [#211] org.eclipse.mylyn.commons.activity -> *.commons.activity.feature

- mylyn.egit/org.eclipse.mylyn.egit.feature/p2.inf
Remove changes to p2.inf that prevented org.eclipse.mylyn.egit.feature
This reverts commit 1a6608db45b4db4f114a852847dc9d0d9c429f19.
Fixes #245
> Revert "[#204] Normalize feature identifiers to simplify support"

- mylyn.reviews/org.eclipse.mylyn.gerrit.core.tests/src/org/eclipse/mylyn/internal/gerrit/core/egit/GerritToGitMappingTest.java
- mylyn.reviews/org.eclipse.mylyn.gerrit.tests/src/org/eclipse/mylyn/gerrit/tests/core/GerritSynchronizationTest.java
- mylyn.reviews/org.eclipse.mylyn.gerrit.tests/src/org/eclipse/mylyn/gerrit/tests/core/client/rest/ChangeInfoTest.java
- mylyn.reviews/org.eclipse.mylyn.gerrit.tests/src/org/eclipse/mylyn/internal/gerrit/core/remote/GerritDataLocatorTest.java
- mylyn.reviews/org.eclipse.mylyn.gerrit.tests/src/org/eclipse/mylyn/internal/gerrit/core/remote/GerritReviewRemoteFactoryJUnit3Test.java
- mylyn.reviews/org.eclipse.mylyn.gerrit.tests/src/org/eclipse/mylyn/internal/gerrit/core/remote/PatchSetDetailRemoteFactoryTest.java
- mylyn.reviews/org.eclipse.mylyn.gerrit.tests/src/org/eclipse/mylyn/internal/gerrit/core/remote/PatchSetRemoteFactoryTest.java
- mylyn.reviews/org.eclipse.mylyn.gerrit.tests/src/org/eclipse/mylyn/internal/gerrit/core/remote/ReviewHarness.java
- mylyn.reviews/org.eclipse.mylyn.gerrit.tests/src/org/eclipse/mylyn/internal/gerrit/core/remote/TestRemoteObserver.java
- mylyn.reviews/org.eclipse.mylyn.gerrit.ui.tests/src/org/eclipse/mylyn/internal/gerrit/ui/editor/GerritTaskEditorPageTest.java
- mylyn.reviews/org.eclipse.mylyn.reviews.core.tests/src/org/eclipse/mylyn/reviews/core/model/CommentContainerTest.java
- mylyn.reviews/org.eclipse.mylyn.reviews.core.tests/src/org/eclipse/mylyn/reviews/core/model/IndexedTest.java
- mylyn.reviews/org.eclipse.mylyn.reviews.core.tests/src/org/eclipse/mylyn/reviews/core/spi/remote/AbstractDataLocatorTest.java
- mylyn.reviews/org.eclipse.mylyn.reviews.core.tests/src/org/eclipse/mylyn/reviews/core/spi/remote/ReviewsDataLocatorTest.java
- mylyn.reviews/org.eclipse.mylyn.reviews.core.tests/src/org/eclipse/mylyn/reviews/core/spi/remote/emf/RemoteEmfFactoryTest.java
- mylyn.reviews/org.eclipse.mylyn.reviews.core.tests/src/org/eclipse/mylyn/reviews/core/spi/remote/emf/RemoteEmfObserverTest.java
- mylyn.reviews/org.eclipse.mylyn.reviews.core.tests/src/org/eclipse/mylyn/reviews/core/spi/remote/emf/RemoteServiceTest.java
- mylyn.reviews/org.eclipse.mylyn.reviews.core.tests/src/org/eclipse/mylyn/reviews/core/spi/remote/emf/TestRemoteEmfObserver.java
- mylyn.reviews/org.eclipse.mylyn.reviews.tests/src/org/eclipse/mylyn/reviews/spi/edit/remote/AbstractRemoteEditFactoryProviderTest.java
- mylyn.reviews/org.eclipse.mylyn.reviews.tests/src/org/eclipse/mylyn/reviews/tests/ui/UiDataLocatorTest.java
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.core.tests/src/org/eclipse/mylyn/bugzilla/rest/core/tests/BugzillaRestClientTest.java
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.core.tests/src/org/eclipse/mylyn/bugzilla/rest/core/tests/BugzillaRestConnectorNoFixtureTest.java
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.core.tests/src/org/eclipse/mylyn/bugzilla/rest/core/tests/BugzillaRestConnectorTest.java
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.core.tests/src/org/eclipse/mylyn/bugzilla/rest/core/tests/BugzillaRestFlagMapperTest.java
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.core.tests/src/org/eclipse/mylyn/bugzilla/rest/test/support/BugzillaRestHarness.java
replaced all imports of ```org.junit.Assert.assertThat``` with
```org.hamcrest.MatcherAssert.assertThat```
> [#252] JUnit's assertThat is deprecated

- mylyn.commons/org.eclipse.mylyn.commons.core/META-INF/MANIFEST.MF
- mylyn.commons/org.eclipse.mylyn.commons.core/src/org/eclipse/mylyn/commons/core/collections/LinkedHashMappArrayListValuedHashMap.java
- mylyn.reviews/org.eclipse.mylyn.reviews.core/src/org/eclipse/mylyn/reviews/internal/core/TaskBuildStatusMapper.java
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/src/org/eclipse/mylyn/internal/tasks/ui/SynchronizeRelevantTasksJob.java
Move newly introduced `LinkedHashMappArrayListValuedHashMap` to a provisional API package.
> [#287] Remove guava

- Jenkinsfile
- org.eclipse.mylyn.releng/oomph/Mylyn.setup
I will use the Branch 315-setup-test to test tat a new Eclipse Installation with Eclipse-Installer has no problems.
When finish, I will remove the branch from mylyn.setup so that we have only the main stream.
> [#315] Deploy Docs Snapshot was not executed and prepare separate Branch for mylyn.setup tests

- mylyn.reviews/org.eclipse.mylyn.gerrit.ui.tests/META-INF/MANIFEST.MF
- mylyn.reviews/org.eclipse.mylyn.reviews.core.tests/META-INF/MANIFEST.MF
- mylyn.reviews/org.eclipse.mylyn.reviews.tests/META-INF/MANIFEST.MF
- mylyn.tasks/connectors/bugzilla-rest/org.eclipse.mylyn.bugzilla.rest.core.tests/META-INF/MANIFEST.MF
- org.eclipse.mylyn-site/category.xml
- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
* Hamcrest 2.x is in latest platform/orbit
* javax.xml.stream is part of jvm so no need for it
* commons-logging is in latest orbit
> Reduce ancient Orbit dependencies usage

- mylyn.builds/org.eclipse.mylyn.builds.ui/META-INF/MANIFEST.MF
- mylyn.context/org.eclipse.mylyn.team.ui/META-INF/MANIFEST.MF
- mylyn.tasks/org.eclipse.mylyn.tasks.ui/META-INF/MANIFEST.MF
Move to
```
Import-Package: org.osgi.service.event;version="1.4.1"
```
Fixed #339
> [#339] Replace dependency to org.eclipse.osgi.services

- .github/dependabot.yml
Dependabot Maven need the pom.xml so we can only use this in mylyn.docs
> [#440] Dependabot only for folder mylyn.docs

- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.maven/pom.xml
Switch `org.eclipse.mylyn.wikitext.maven` to fixed versions ofr Mylyn Docs until we restore Maven publishing with #459
> [#469] Prepare releng for 4.3.0

- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.maven/pom.xml
Revert the fix for wikitext maven plugin dependencies
> [#459] Restore releng for publishing Maven Docs to maven central

- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core.test/META-INF/MANIFEST.MF
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core.test/src/org/eclipse/mylyn/internal/gitlab/core/GitlabRestClientTest.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabRepositoryConnector.java
- mylyn.tasks/connectors/gitlab/org.eclipse.mylyn.gitlab.core/src/org/eclipse/mylyn/internal/gitlab/core/GitlabRestClient.java
`GET /projects/:id` respond with a list of Repository feature toggle states.
Fix for #501 checks if
```json
{
...
"issues_enabled": <boolean>
...
}
```
is set to `true`, then fetches Milestones. Otherwise, just returns an empty array.
> Check that GitLab Repository has Issues enabled before fetching repo Milestones (#501)

- org.eclipse.mylyn-site/category.xml
With the addition of dependencies on org.apache.tika.core, it's needed in the update site.
https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/517
> Add org.apache.tika.core to the category.xml

- org.eclipse.mylyn.releng/launcher/mylyn clean.launch
- org.eclipse.mylyn.releng/launcher/mylyn install.launch
- org.eclipse.mylyn.releng/launcher/mylyn verify.launch
- org.eclipse.mylyn.releng/oomph/Mylyn.setup
- Specify property user.home=${system_property:user.home} for the m2e launchers so that the user.home of the launched process necessarily matches the user.home of the launching application.
- Add a preference task to show Oomph's tiny two-button setup tool bar.
- Set the eclipse.target.platform variable to None to avoid a prompt for something not intended to be used.
- Set IDs on tasks that are reference to avoid references that are positional which might be corrupted by textual editing.
- Configure clones configure new branches to rebase.
- Configure core/autocrlf to input.
- Set the console to be of unlimited outputsize with tab width of 4.
> Improve the Oomph setup and m2e launchers

- org.eclipse.mylyn.releng/oomph/Mylyn.setup
- Don't specify the Oomph update site URL for the p2 director task because a site is always provide by Oomph itself.  The site varies depending on which installer is used, i.e., a nightly site for a nightly installer versus a milestone site for a milestone/release installer.
- Also create a .gitignore that ignores itself and the created .project file to ensure that the .github organization clone is not dirty.
> Tiny improvements to the Oomph setup

- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext.textile/.project
- mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext/.project
- org.eclipse.mylyn.releng/oomph/Mylyn.setup
- Ensure that the two projects referenced as dependency by org.eclipse.mylyn.wikitext.maven have an m2e nature and build so that the dependencies resolve to those workspace projects.
https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/552
> Eliminate long maven build from the setup

- mylyn.builds/org.eclipse.mylyn.jenkins.core/META-INF/MANIFEST.MF
- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
- Use version 1.0.3 which is newer than all the current 2.x versions
https://github.com/eclipse-simrel/simrel.build/issues/438
The 2.5.0 versions are all older than the 1.0.3 version:
https://repo1.maven.org/maven2/org/glassfish/hk2/osgi-resource-locator/
> Use org.glassfish.hk2.osgi-resource-locator from latest Orbit

- mylyn.commons/org.eclipse.mylyn.commons.core/META-INF/MANIFEST.MF
- mylyn.commons/org.eclipse.mylyn.commons.core/src/org/eclipse/mylyn/commons/core/HtmlStreamTokenizer.java
- mylyn.commons/org.eclipse.mylyn.commons.net/META-INF/MANIFEST.MF
- mylyn.commons/org.eclipse.mylyn.commons.net/src/org/eclipse/mylyn/commons/net/HtmlStreamTokenizer.java
- mylyn.commons/org.eclipse.mylyn.commons.net/src/org/eclipse/mylyn/commons/net/WebUtil.java
- mylyn.reviews/org.eclipse.mylyn.gerrit.core/META-INF/MANIFEST.MF
- mylyn.reviews/org.eclipse.mylyn.gerrit.core/src/org/eclipse/mylyn/internal/gerrit/core/client/GerritHtmlProcessor.java
- org.eclipse.mylyn-site/category.xml
- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
- org.eclipse.mylyn.releng/launcher/mylyn verify.launch
lang3.StringEscapeUtils was deprecated in 3.6 and replaced by text.StringEscapeUtils
Eclipse is showing an error complaining about 'The method ... has been removed' and I have no idea where that is coming from or how to get rid of if?
> 577 replace orgapachecommonslang3stringescapeutils with orgapachecommonstextstringescapeutils

- mylyn.docs/pom.xml
- mylyn.releng/org.eclipse.mylyn.parent/pom.xml
tycho 4.0.9 (and JGit 6.9.0) fixes the missing class complaint at the end of the maven run
Task-Url: https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/issues/626
> Bump tycho to 4.0.9 #495

- org.eclipse.mylyn-site/category.xml
- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
- The 9.12 version of org.apache.lucene.sandbox has a new dependency on that bundle.
- Update the target platform to use the 4.34 release repository.
> Include org.apache.lucene.facet in the update site

- .gitignore
- .mvn/develocity.xml
- .mvn/extensions.xml
- Jenkinsfile
This PR will enable you to publish Build Scans to [develocity-staging.eclipse.org](https://develocity-staging.eclipse.org) as requested [here](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5409).
This PR publishes a build scan for every CI build and for every local build from an authenticated Eclipse committer. The build will not fail if publishing fails. Local and remote caching was left disabled on this PR by design so that the build is not affected by this change.
The build scans of the Eclipse Mylyn project are published to the Develocity instance at [develocity-staging.eclipse.org](https://develocity-staging.eclipse.org), hosted by the Eclipse Foundation and run in partnership between the Eclipse and Gradle. This Develocity instance has all features and extensions enabled …
> Develocity configuration

- .mvn/extensions.xml
Update the Develocity extension version to 1.23.2, which brings support for Tycho test result discovery. This allows you to use build scans to view test failures and the exact reason for those, instead of getting the test report / searching through the console log, which can be especially useful on CI.
> Bump Develocity extension version

- .mvn/extensions.xml
- Jenkinsfile
- mylyn.releng/org.eclipse.mylyn.parent/pom.xml
- org.eclipse.mylyn.tests/pom.xml
This PR will re-enable Develocity and enable caching for Tycho tests, as added in PR https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/718. 
I hope this is a good time to do this. As discussed already, the reason for you disabling it in the first place was problems with the Eclipse infrastructure, related to Jenkins vaults, which is how secrets are managed for Develocity for Eclipse projects.
> Re-enable Develocity

- org.eclipse.mylyn-target/org.eclipse.mylyn.target.target
https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/868
> Use 4.38-I-builds because all 4.37-I-builds are deleted
